cluster.name: cluster-vagrant

node.name: es-data-02

node.data: true

network.host: [_local_, _site_]

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

discovery.seed_hosts: ["10.0.0.11"]
cluster.initial_master_nodes: ["es-master"]

node.master: false
node.ingest: false
node.ml: false
node.voting_only: false

xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate 
xpack.security.transport.ssl.keystore.path: tmp-elasticsearch-certificate
xpack.security.transport.ssl.truststore.path: tmp-elasticsearch-certificate
